SELECT * FROM SCHOOL_DAY;
SELECT * FROM INSTRUCTOR;
SELECT * FROM ATTENDANCE_DAY;
SELECT * FROM ROOM;
SELECT * FROM DISCIPLINE;
SELECT * FROM SUBJECT;
SELECT * FROM HOMEROOM;
SELECT * FROM HOMEROOM_DAY;
SELECT * FROM BLOCK;
SELECT * FROM LANE ORDER BY block_id;
SELECT * FROM COURSE;
SELECT * FROM COURSE_DETAIL;
SELECT * FROM LANE_COURSE;

-- Homeroomテーブルにgrade列を追加
ALTER TABLE HOMEROOM 
ADD COLUMN grade SMALLINT;

-- Subjectテーブルにgrade列を追加
ALTER TABLE SUBJECT 
ADD COLUMN grade SMALLINT;
